### PR TITLE
Add a show module

### PR DESCRIPTION
**Pull request by dorafmon**

### CODE REVIEW

**Comment by bordoley** [comment]
s/Show/Stringable.
s/show/toString

that said see my concerns Re: ocaml strings in general regarding unicode. In bs, is there clean interop between ocaml strings and js strings?

**Comment by dorafmon** [comment]
@bordoley  See [this link](http://bloomberg.github.io/bucklescript/Manual.html#_unicode_support_since_1_5_1), what I am thinking is to have a utf8 module and provide two implementations, one for js to directly use this feature, and one for ocaml, which we build for our own or borrow ideas from other projects.

**Comment by bordoley** [comment]
To make sure we're on the same page here, UTF-8 is not the runtime encoding of strings in JavaScript. UCS2 (effectively UTF-16) is. I think supporting UTF-8 conversion for serialization purposes is interesting on the server side, but in js you're like converting to/from JSON, so I'm not sure UTF-8 support is very valuable in that context.

**Comment by glennsl** [comment]
I also share the concerns regarding unicode and interoperability, but Unicode-support isn't really a blocker on this PR is it?

**Pull request merged**
